### ISSUE TITLE
missing requirements-dev.txt

### ISSUE THREAD

**Issue by bobdingAI** [eclipse-zenoh-flow/zenoh-flow-python#1]
1 missing requirements-dev.txt

2. python setup.py bdist_wheel failed

**Comment by gabrik** [comment]
Hi @bobd988, the `requirements-dev.txt` file is there: https://github.com/atolab/zenoh-flow-python/blob/master/zenoh-flow-python/requirements-dev.txt 

We are updating the readme to be more precise
