### ISSUE TITLE
Rename DataSender and DataReceiver into Output and Input

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh-flow/zenoh-flow-python#15]
As discussed, to have a coherent API across languages we should rename the following:
- `DataSender` -> `Output`
- `DataReceiver` -> `Input`

**Comment by gabrik** [comment]
Done in https://github.com/ZettaScaleLabs/zenoh-flow-python/commit/95f38d8f2bc495c8789bba0ee963338faeddc987
