### ISSUE TITLE
Error when reading pipeline.yaml file

### ISSUE THREAD

**Issue by kkhao** [eclipse-zenoh-flow/zenoh-flow-python#6]
When I configure the _configuration_ parameter as follows:
```
configuration:
      threshold: 0.3
```
I got the following error:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', zenoh-flow-python-types/src/utils.rs:39:60
```
But when I set the _threshold_ to 3, there is no error, that is to say, this error will occur with float, and the int type will not.

**Comment by gabrik** [comment]
Hi @kkhao  this is related to: https://github.com/ZettaScaleLabs/zenoh-flow-python/blob/master/zenoh-flow-python-types/src/utils.rs#L39

As seems that `serde_json::json` does not expose the actual type of `Number`.

We need to address this.
